<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\data\relics\v0.111\relic-catalog.json"
                      Link="Data\relics\v0.111\relic-catalog.json" />
  </ItemGroup>
</Project>
