"""Bounded, nonformal StudentV2 training; the default CLI only reports readiness.

A prepared corpus is not an authorization to fit. A quality acceptance and a
separate authorization must bind the exact frozen inputs and lifetime budget.
Neither is generated by this module. Test shards are verified as opaque bytes;
their records and labels never enter a model, metric, or checkpoint selection.
"""
from __future__ import annotations

import argparse
from copy import deepcopy
import hashlib
import json
import math
import os
from pathlib import Path
import random
import time

import torch
from torch.nn import functional as F

from .data import canonical_object_digest
from .inference_v2 import (POLICY_ACTION_KINDS, POLICY_COVERAGE_KEYS, SUPERVISION_FORMAT, SUPERVISION_PROGRESS_FORMAT,
                           implementation_fingerprint as inference_fingerprint, valid_supervision_coverage)
from .model_v2 import StudentV2
from .public_identity_v2 import PUBLIC_IDENTITY_SCHEME, public_input_digest
from .reproducibility import SOURCE_FILES, implementation_fingerprint as base_fingerprint, source_hashes
from .schema import HEADS, SchemaError, integer
from .schema_v2 import MODEL_VERSION, PLAN_HEADS, PUBLIC_SCHEMA, load_config, validate_config
from .smoke_v2 import decision_loss
from .train import atomic_save, config_hash, distribution_target, seed_everything, validate_pilot_budget

CHECKPOINT_FORMAT = "nosl.experimental.checkpoint.v2"
QUALITY_FORMAT = "nosl.training.quality-acceptance.v2"
AUTHORIZATION_FORMAT = "nosl.training.authorization.v2"
V2_TRAINING_SOURCES = tuple(dict.fromkeys((*SOURCE_FILES, "schema_v2.py", "model_v2.py",
    "inference_v2.py", "public_identity_v2.py", "data_v2.py", "smoke_v2.py", "train_v2.py")))
EXTRA_SOURCE_FILES = ("tools/prepare_dataset.py",)


def implementation_fingerprint() -> dict:
    """Bind every imported v1 helper, v2 source, preparation source and CPU runtime."""
    value = base_fingerprint()
    value.update(format="nosl.training.implementation.v2", model_version=MODEL_VERSION,
                 source_sha256=source_hashes(V2_TRAINING_SOURCES))
    root = Path(__file__).resolve().parents[2]
    try:
        value["source_sha256"].update({name: hashlib.sha256((root / name).read_bytes()).hexdigest()
                                       for name in EXTRA_SOURCE_FILES})
    except OSError as error:
        raise SchemaError("cannot verify v2 preparation source") from error
    return value


def has_supervision(record: dict, config: dict) -> bool:
    """Only targets contributing to an enabled loss count as supervision."""
    targets, weights = record["targets"], config["base_config"]["loss_weights"]
    equivalent = set(targets["equivalent_action_set"])
    legal = {i for i, allowed in enumerate(record["public_input"]["legal_mask"]) if allowed}
    return (any(row.get("sample_weight", 1) > 0 and any(row["masks"][head] and weights[head] > 0
                for head in HEADS) for row in targets["actions"])
            or weights["pairwise"] > 0 and any(pair["weight"] > 0 for pair in targets["pairwise"])
            or weights["equivalent"] > 0 and bool(equivalent) and equivalent < legal
            or any(targets.get("plan", {}).get("masks", {}).get(head, False)
                   and config["plan_loss_weights"][head] > 0 for head in PLAN_HEADS))


def supervision_coverage(records: list[dict], config: dict) -> dict:
    """Count available positive-weight masks and enabled losses, including policy scope.

    A value-policy root has at least two legal actions and available positive-
    weight value targets for every legal action. Pairwise supervision requires
    an enabled positive pair between two such actions. An equivalent set must
    be a proper subset of legal actions; maximizing the entire set is no signal.
    Only inactive-controller roots establish inactive action-policy coverage.
    """
    result = {"format": SUPERVISION_FORMAT, "roots": len(records),
              "action_heads": {head: {"masked_rows": 0, "loss_rows": 0, "loss_roots": 0} for head in HEADS},
              "plan_heads": {head: {"masked_roots": 0, "loss_roots": 0} for head in PLAN_HEADS},
              "policy_action_kinds": {kind: 0 for kind in POLICY_ACTION_KINDS},
              "action_policy": {key: 0 for key in POLICY_COVERAGE_KEYS}}
    weights = config["base_config"]["loss_weights"]
    for record in records:
        public, targets = record["public_input"], record["targets"]
        legal = {index for index, allowed in enumerate(public["legal_mask"]) if allowed}
        by_index = {row["action_index"]: row for row in targets["actions"]}
        for head in HEADS:
            count = sum(row["action_index"] in legal and row.get("sample_weight", 1) > 0 and row["masks"][head]
                        for row in targets["actions"])
            result["action_heads"][head]["masked_rows"] += count
            if weights[head] > 0:
                result["action_heads"][head]["loss_rows"] += count
                result["action_heads"][head]["loss_roots"] += count > 0
        for head in PLAN_HEADS:
            available = bool(targets.get("plan", {}).get("masks", {}).get(head, False))
            result["plan_heads"][head]["masked_roots"] += available
            result["plan_heads"][head]["loss_roots"] += available and config["plan_loss_weights"][head] > 0
        if public["controller_context"]["status"] != "inactive" or len(legal) < 2: continue
        valued = {i for i in legal if by_index[i]["masks"]["value"] and by_index[i].get("sample_weight", 1) > 0}
        value = weights["value"] > 0 and valued == legal
        pairs = sum(pair["weight"] > 0 and pair["preferred"] != pair["other"]
                    and pair["preferred"] in valued and pair["other"] in valued for pair in targets["pairwise"])
        pairs = pairs if weights["pairwise"] > 0 else 0
        equivalent = set(targets["equivalent_action_set"])
        equivalence = weights["equivalent"] > 0 and bool(equivalent) and equivalent < legal and valued == legal
        policy = result["action_policy"]
        policy["value_roots"] += value
        policy["pairwise_roots"] += pairs > 0
        policy["pairwise_pairs"] += pairs
        policy["equivalent_roots"] += equivalence
        policy["eligible_roots"] += value or pairs > 0 or equivalence
        supervised_actions = set(legal) if value or equivalence else set()
        if pairs:
            for pair in targets["pairwise"]:
                if pair["weight"] > 0 and pair["preferred"] in valued and pair["other"] in valued:
                    supervised_actions.update((pair["preferred"], pair["other"]))
        for index in supervised_actions:
            result["policy_action_kinds"][public["candidate_actions"][index]["kind"]] += 1
    return result


def empty_supervision_progress(config: dict) -> dict:
    return {"format": SUPERVISION_PROGRESS_FORMAT, "optimizer_steps": 0, "action_policy_optimizer_steps": 0,
            "consumed": supervision_coverage([], config)}


def _record_committed_supervision(progress: dict, records: list[dict], config: dict) -> None:
    batch = supervision_coverage(records, config)
    progress["optimizer_steps"] += 1
    progress["action_policy_optimizer_steps"] += batch["action_policy"]["eligible_roots"] > 0
    consumed = progress["consumed"]
    consumed["roots"] += batch["roots"]
    for section in ("action_heads", "plan_heads"):
        for head, counts in batch[section].items():
            for key, count in counts.items(): consumed[section][head][key] += count
    for key in POLICY_COVERAGE_KEYS: consumed["action_policy"][key] += batch["action_policy"][key]
    for key in POLICY_ACTION_KINDS: consumed["policy_action_kinds"][key] += batch["policy_action_kinds"][key]


def check_split_isolation(train, validation) -> None:
    for name, values in (("recomputed v2 public input", lambda row: public_input_digest(row["public_input"])),
                         *((key, lambda row, key=key: row["audit_only"].get(key)) for key in
                           ("source_run_group", "source_combat_id", "branch_family", "public_state_digest"))):
        left, right = ({values(row) for row in data.records} for data in (train, validation))
        if any(not isinstance(value, str) or not value for value in left | right):
            raise SchemaError("missing split provenance: " + name)
        if left & right:
            raise SchemaError("train/validation leakage in " + name)


def freeze_inputs(datasets: dict, config: dict) -> dict:
    """Verify prepared train/validation and bind the complete opaque test manifest."""
    from .data_v2 import PreparedDatasetV2
    validate_config(config)
    if set(datasets) != {"train", "validation"}:
        raise SchemaError("v2 fitting accepts prepared train/validation only; never load test labels")
    for split, data in datasets.items():
        if not isinstance(data, PreparedDatasetV2) or data.split != split:
            raise SchemaError("v2 fitting requires matching PreparedDatasetV2 splits")
        data.verify_integrity()
        manifest_bytes = data.path.read_bytes()
        if (hashlib.sha256(manifest_bytes).hexdigest() != data.manifest_sha256
                or json.loads(manifest_bytes) != data.manifest):
            raise SchemaError("prepared v2 manifest changed after loading")
        if not len(data):
            raise SchemaError("prepared " + split + " split is empty")
    train, validation = datasets["train"], datasets["validation"]
    if (train.manifest_sha256 != validation.manifest_sha256 or train.manifest != validation.manifest
            or train.path.resolve() != validation.path.resolve()):
        raise SchemaError("train/validation must bind the same prepared dataset manifest")
    manifest = train.manifest
    if (manifest.get("public_identity_scheme") != PUBLIC_IDENTITY_SCHEME
            or manifest.get("isolation_passed") is not True
            or manifest.get("lock", {}).get("student_config_sha256") != canonical_object_digest(config)):
        raise SchemaError("prepared v2 identity, isolation or configuration mismatch")
    check_split_isolation(train, validation)
    counts = {split: {"roots": len(data),
                     "supervised_roots": sum(has_supervision(row, config) for row in data.records),
                     "engineering_roots": sum(row["audit_only"].get("engineering_smoke") is True for row in data.records),
                     "nontrainable_roots": sum(row["audit_only"].get("trainable") is False for row in data.records)}
              for split, data in datasets.items()}
    # The verified manifest binds all stage reports and shards, including frozen
    # test hashes. No test JSONL is parsed here or by the prepared loader.
    return {"format": "nosl.training.inputs.v2", "model_version": MODEL_VERSION,
            "public_schema": PUBLIC_SCHEMA, "public_identity_scheme": PUBLIC_IDENTITY_SCHEME,
            "config_sha256": config_hash(config), "implementation": implementation_fingerprint(),
            "dataset_manifest_sha256": train.manifest_sha256,
            "dataset_manifest": deepcopy(manifest),
            "splits": {split: {"sha256": data.sha256, "records_sha256": config_hash(data.records), **counts[split]}
                       for split, data in datasets.items()},
            "training_supervision": supervision_coverage(train.records, config),
            "frozen_test_shards": deepcopy(manifest["frozen_test_shards"]),
            "test_labels_read": False, "test_evaluated": False, "test_used_for_model_selection": False}


def quality_gate(frozen: dict, budget: dict | None = None, *, quality_record: dict | None = None,
                 authorization: dict | None = None) -> dict:
    """Return a fail-closed admission decision; never manufacture acceptance.

    Quality record fields: format=QUALITY_FORMAT, accepted=true,
    frozen_inputs_sha256, reviewed_by, assessment. Authorization fields:
    format=AUTHORIZATION_FORMAT, authorized=true, purpose=bounded_nonformal_pilot,
    frozen_inputs_sha256, quality_acceptance_sha256, authorization_id, budget.
    Human review covers target quality, unresolved mass, throughput and coverage;
    numeric sample counts alone do not grant acceptance or authorization.
    """
    reasons = []
    digest = config_hash(frozen)
    manifest = frozen.get("dataset_manifest", {})
    if frozen.get("format") != "nosl.training.inputs.v2": reasons.append("verified_v2_inputs_required")
    if manifest.get("lock", {}).get("mode") != "pilot": reasons.append("pilot_corpus_required")
    if manifest.get("isolation_passed") is not True: reasons.append("split_isolation_required")
    shards = frozen.get("frozen_test_shards")
    if (not isinstance(shards, list) or not shards
            or any(not isinstance(shard, dict) or type(shard.get("rows")) is not int or shard["rows"] < 0 for shard in shards)
            or sum(shard["rows"] for shard in shards) == 0):
        reasons.append("opaque_frozen_test_shards_required")
    if any(frozen.get(key) is not False for key in ("test_labels_read", "test_evaluated", "test_used_for_model_selection")):
        reasons.append("test_labels_must_remain_unread")
    for split in ("train", "validation"):
        counts = frozen.get("splits", {}).get(split, {})
        if counts.get("supervised_roots", 0) <= 0: reasons.append(split + "_usable_supervision_required")
        if counts.get("engineering_roots", 0): reasons.append("engineering_smoke_cannot_fit")
        if counts.get("nontrainable_roots", 0): reasons.append("nontrainable_records_cannot_fit")
    try:
        if budget is None: raise SchemaError("missing budget")
        validate_pilot_budget(**budget, dataset_roots=frozen.get("splits", {}).get("train", {}).get("roots", 0))
    except (SchemaError, TypeError):
        reasons.append("explicit_valid_lifetime_budget_required")
    quality_valid = (isinstance(quality_record, dict) and quality_record.get("format") == QUALITY_FORMAT
                     and quality_record.get("accepted") is True and quality_record.get("frozen_inputs_sha256") == digest
                     and all(isinstance(quality_record.get(key), str) and quality_record[key].strip()
                             for key in ("reviewed_by", "assessment")))
    if not quality_valid: reasons.append("explicit_matching_quality_acceptance_required")
    authorization_valid = (isinstance(authorization, dict) and authorization.get("format") == AUTHORIZATION_FORMAT
                           and authorization.get("authorized") is True
                           and authorization.get("purpose") == "bounded_nonformal_pilot"
                           and authorization.get("frozen_inputs_sha256") == digest
                           and quality_valid
                           and authorization.get("quality_acceptance_sha256") == config_hash(quality_record)
                           and authorization.get("budget") == budget
                           and isinstance(authorization.get("authorization_id"), str)
                           and bool(authorization["authorization_id"].strip()))
    if not authorization_valid: reasons.append("explicit_matching_bounded_authorization_required")
    return {"accepted": not reasons, "status": "AUTHORIZED_BOUNDED_NONFORMAL_PILOT" if not reasons else "FIT_BLOCKED",
            "reasons": sorted(set(reasons)), "frozen_inputs_sha256": digest,
            "formal_training_run": False, "automatic_training_authorized": False}


def _bound_frozen(model: StudentV2, frozen: dict) -> dict:
    if any(value.device.type != "cpu" for value in (*model.parameters(), *model.buffers())):
        raise SchemaError("bounded v2 checkpoints support CPU model and RNG state only")
    implementation, digest = implementation_fingerprint(), config_hash(model.config)
    if "implementation" in frozen and frozen["implementation"] != implementation:
        raise SchemaError("v2 implementation, runtime or CPU settings changed")
    if "config_sha256" in frozen and frozen["config_sha256"] != digest:
        raise SchemaError("v2 configuration changed")
    return {**deepcopy(frozen), "implementation": implementation, "config_sha256": digest}


def _validate_progress(state: dict, frozen: dict, budget: dict, config: dict) -> None:
    if not {"optimizer_steps", "epoch", "offset", "order", "trace", "optimizer"} <= state.keys():
        raise SchemaError("v2 checkpoint progress fields missing")
    roots = frozen.get("splits", {}).get("train", {}).get("roots")
    validate_pilot_budget(**budget, dataset_roots=roots if roots is not None else 0)
    integer(state["optimizer_steps"], "v2 checkpoint steps", 0, budget["max_steps"])
    integer(state["epoch"], "v2 checkpoint epoch", 0, budget["max_epochs"])
    order = state["order"]
    if not isinstance(order, list) or any(type(index) is not int for index in order):
        raise SchemaError("invalid v2 checkpoint shuffle order")
    if order and (len(order) > budget["max_roots"] or (roots is not None and len(order) != roots)
                  or set(order) != set(range(len(order))) or len(set(order)) != len(order)):
        raise SchemaError("invalid v2 checkpoint shuffle order")
    integer(state["offset"], "v2 checkpoint offset", 0, len(order))
    if (order and state["offset"] == len(order)) or (state["epoch"] == budget["max_epochs"] and order):
        raise SchemaError("invalid v2 checkpoint epoch boundary")
    if not isinstance(state["trace"], list): raise SchemaError("invalid v2 checkpoint trace")
    if any(not isinstance(entry, dict) for entry in state["trace"]):
        raise SchemaError("invalid v2 checkpoint trace entry")
    optimizer_state = state["optimizer"].get("state") if isinstance(state["optimizer"], dict) else None
    if not isinstance(optimizer_state, dict): raise SchemaError("invalid v2 optimizer state")
    if state["optimizer_steps"] == 0 and optimizer_state:
        raise SchemaError("zero-step v2 checkpoint cannot contain learned optimizer state")
    progress = state.get("supervision_progress")
    if (not isinstance(progress, dict) or progress.get("format") != SUPERVISION_PROGRESS_FORMAT
            or progress.get("optimizer_steps") != state["optimizer_steps"]
            or not valid_supervision_coverage(progress.get("consumed"), config)):
        raise SchemaError("v2 checkpoint lacks valid committed supervision coverage")
    policy_steps = progress.get("action_policy_optimizer_steps")
    integer(policy_steps, "action-policy optimizer steps", 0, state["optimizer_steps"])
    if state["optimizer_steps"] == 0 and progress != empty_supervision_progress(config):
        raise SchemaError("zero-step v2 checkpoint cannot claim consumed supervision")
    if not policy_steps <= progress["consumed"]["action_policy"]["eligible_roots"] <= policy_steps * config["base_config"]["batch_size"]:
        raise SchemaError("v2 checkpoint action-policy coverage disagrees with committed steps")
    if not state["optimizer_steps"] <= progress["consumed"]["roots"] <= state["optimizer_steps"] * config["base_config"]["batch_size"]:
        raise SchemaError("v2 checkpoint supervision coverage disagrees with committed steps")
    if state["optimizer_steps"] > 0:
        admission = frozen.get("admission", {})
        gate = quality_gate({key: value for key, value in frozen.items() if key != "admission"}, budget,
                            quality_record=admission.get("quality_record"), authorization=admission.get("authorization"))
        if not gate["accepted"]:
            raise SchemaError("learned v2 checkpoint lacks matching quality acceptance and authorization")
        adam_steps = []
        for value in optimizer_state.values():
            step = value.get("step") if isinstance(value, dict) else None
            if isinstance(step, torch.Tensor) and step.numel() == 1: step = float(step)
            if (type(step) not in (int, float) or not math.isfinite(step)
                    or int(step) != step or not 1 <= step <= state["optimizer_steps"]):
                raise SchemaError("v2 optimizer state disagrees with lifetime steps")
            adam_steps.append(step)
        if not adam_steps or max(adam_steps) != state["optimizer_steps"]:
            raise SchemaError("v2 optimizer state disagrees with lifetime steps")
        baseline = [entry for entry in state["trace"] if entry.get("phase") == "before_fit_random_initialization"]
        if len(baseline) != 1 or baseline[0].get("optimizer_steps") != 0 or baseline[0].get("epoch") != 0:
            raise SchemaError("learned v2 checkpoint lacks a valid random-initialization reference")


def checkpoint_state(model: StudentV2, optimizer, frozen: dict, budget: dict, epoch: int, offset: int,
                     steps: int, order: list[int], trace: list[dict], *, supervision_progress: dict | None = None) -> dict:
    """Zero-step engineering snapshots are explicitly untrained and need no fit grant."""
    frozen = _bound_frozen(model, frozen)
    state = {"format": CHECKPOINT_FORMAT, "model_version": MODEL_VERSION,
             "model": deepcopy(model.state_dict()), "optimizer": deepcopy(optimizer.state_dict()),
             "optimizer_class": type(optimizer).__module__ + "." + type(optimizer).__qualname__,
             "frozen": frozen, "budget": deepcopy(budget), "epoch": epoch, "offset": offset,
             "optimizer_steps": steps, "order": list(order), "trace": deepcopy(trace),
             "supervision_progress": deepcopy(supervision_progress) if supervision_progress is not None else empty_supervision_progress(model.config),
             "torch_rng": torch.get_rng_state(), "python_rng": random.getstate(),
             "trained": steps > 0, "formal_training_run": False, "promoted": False}
    _validate_progress(state, frozen, budget, model.config)
    return state


def restore_checkpoint(path: str | Path, model: StudentV2, optimizer, frozen: dict, budget: dict) -> dict:
    state = torch.load(path, map_location="cpu", weights_only=True)
    if (not isinstance(state, dict) or state.get("format") != CHECKPOINT_FORMAT
            or state.get("model_version") != MODEL_VERSION or state.get("formal_training_run") is not False
            or state.get("promoted") is not False):
        raise SchemaError("checkpoint is not an unpromoted nonformal v2 pilot")
    saved = state.get("frozen")
    if not isinstance(saved, dict) or not isinstance(saved.get("implementation"), dict):
        raise SchemaError("v2 checkpoint lacks implementation provenance")
    expected = _bound_frozen(model, frozen)
    if saved.get("implementation") != expected["implementation"]:
        raise SchemaError("v2 implementation, runtime or CPU settings changed")
    if saved != expected:
        raise SchemaError("v2 resume rejected: configuration, input bytes, provenance or admission changed")
    if state.get("budget") != budget:
        raise SchemaError("resume cannot expand or reset the authorized lifetime v2 budget")
    if state.get("optimizer_class") != type(optimizer).__module__ + "." + type(optimizer).__qualname__:
        raise SchemaError("v2 optimizer implementation changed")
    _validate_progress(state, saved, budget, model.config)
    if state.get("trained") is not (state["optimizer_steps"] > 0):
        raise SchemaError("v2 checkpoint trained status disagrees with optimizer progress")
    model.load_state_dict(state["model"], strict=True)
    optimizer.load_state_dict(state["optimizer"])
    torch.set_rng_state(state["torch_rng"])
    random.setstate(state["python_rng"])
    return state


def evaluate(model: StudentV2, dataset) -> dict:
    """Masked validation metrics; null/count=0 means unavailable, never target zero."""
    if getattr(dataset, "split", None) != "validation":
        raise SchemaError("v2 evaluation accepts validation only; test labels are sealed")
    names = ("loss", "win_brier", "death_brier", "hp_mae", "hp_distribution_cross_entropy",
             "value_mae", "value_mse", "potion_net_change_mae", "equivalent_set_agreement",
             "empirical_teacher_mean_regret", "empirical_teacher_best_action_agreement",
             "plan_success_brier", "plan_extra_net_hp_loss_mae", "plan_extra_net_hp_loss_mse")
    values = {name: [] for name in names}
    pairs, unresolved, missing_plans, incomplete_roots, single_roots = [], 0, 0, 0, 0
    was_training = model.training
    model.eval()
    try:
        with torch.no_grad():
            for record in dataset.records:
                public, targets = record["public_input"], record["targets"]
                output = model(public)
                loss, _ = decision_loss(output, targets, public, model.config)
                if not torch.isfinite(loss): raise RuntimeError("non-finite v2 validation loss")
                values["loss"].append(float(loss))
                for row in targets["actions"]:
                    index = row["action_index"]
                    unresolved += not any(row["masks"].values())
                    if row.get("sample_weight", 1) <= 0: continue
                    for head, name in (("win_probability", "win_brier"), ("death_probability", "death_brier")):
                        if row["masks"][head]: values[name].append((float(output[head][index].sigmoid()) - row[head]) ** 2)
                    for head, name, scale in (("expected_final_hp", "hp_mae", 100), ("value", "value_mae", 100),
                                               ("potion_net_change", "potion_net_change_mae", 1)):
                        if row["masks"][head]:
                            error = float(output[head][index]) * scale - row[head]
                            values[name].append(abs(error))
                            if head == "value": values["value_mse"].append(error ** 2)
                    if row["masks"]["hp_distribution"]:
                        prediction = output["hp_distribution"][index]
                        target = distribution_target(row["hp_distribution"], model.config["base_config"], prediction.device)
                        values["hp_distribution_cross_entropy"].append(float(-(target * F.log_softmax(prediction, -1)).sum()))
                legal = [i for i, allowed in enumerate(public["legal_mask"]) if allowed]
                by_index = {row["action_index"]: row for row in targets["actions"]}
                if len(legal) < 2: single_roots += 1
                elif not all(by_index[i]["masks"]["value"] and by_index[i].get("sample_weight", 1) > 0 for i in legal):
                    incomplete_roots += 1
                else:
                    selected = int(output["ranking_score"].argmax())
                    regret = max(by_index[i]["value"] for i in legal) - by_index[selected]["value"]
                    values["empirical_teacher_mean_regret"].append(max(0., regret))
                    values["empirical_teacher_best_action_agreement"].append(float(abs(regret) <= 1e-9))
                for pair in targets["pairwise"]:
                    if pair["weight"] > 0:
                        delta = float(output["value"][pair["preferred"]] - output["value"][pair["other"]])
                        pairs.append((float(delta > 0) + .5 * float(delta == 0), pair["weight"]))
                if targets["equivalent_action_set"]:
                    values["equivalent_set_agreement"].append(float(int(output["ranking_score"].argmax()) in targets["equivalent_action_set"]))
                plan = targets.get("plan")
                missing_plans += not plan or not any(plan["masks"].values())
                if plan and plan["masks"]["specified_success_probability"]:
                    values["plan_success_brier"].append((float(output["plan"]["specified_success_probability"].sigmoid()) - plan["specified_success_probability"]) ** 2)
                if plan and plan["masks"]["extra_net_hp_loss"]:
                    error = float(output["plan"]["extra_net_hp_loss"]) * 100 - plan["extra_net_hp_loss"]
                    values["plan_extra_net_hp_loss_mae"].append(abs(error))
                    values["plan_extra_net_hp_loss_mse"].append(error ** 2)
    finally:
        model.train(was_training)
    if any(not math.isfinite(value) for group in values.values() for value in group):
        raise RuntimeError("non-finite v2 validation metrics")
    result = {name: {"value": sum(group) / len(group) if group else None, "count": len(group)} for name, group in values.items()}
    result["pairwise_agreement"] = {"value": sum(a * w for a, w in pairs) / sum(w for _, w in pairs) if pairs else None,
                                    "count": len(pairs)}
    result.update(evaluation_roots=len(dataset.records), unresolved_actions=unresolved, unavailable_plan_roots=missing_plans,
                  probabilities_calibrated=False, test_evaluated=False, safe_learned_plan_execution_verified=False,
                  action_metric_weighting="unweighted over masked positive-weight rows; pairwise agreement uses pair weights",
                  empirical_teacher_ranking_semantics={"single_action_roots_skipped": single_roots,
                      "incomplete_value_roots_skipped": incomplete_roots, "uncertainty_accounted_for": False,
                      "statistically_certified": False, "student_rollout_win_rate_measured": False,
                      "population": "all legal positive-weight value targets available, at least two legal candidates",
                      "warning": "finite-sample empirical teacher means, not certified ranking or closed-loop student performance"},
                  plan_metric_scope="masked whole_plan_from_anchor labels only; no learned continuation or budget guarantee")
    return result


def _write_json(value, path: Path) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def export_bundle(model: StudentV2, output: str | Path, *, frozen: dict, budget: dict,
                  optimizer_steps: int = 0, metadata: dict | None = None,
                  supervision_progress: dict | None = None) -> dict:
    """Export a v2-compatible bundle; zero-step engineering bundles stay untrained."""
    output = Path(output)
    bound = _bound_frozen(model, frozen)
    integer(optimizer_steps, "bundle optimizer steps", 0, budget["max_steps"])
    if optimizer_steps:
        admission = bound.get("admission", {})
        gate = quality_gate({k: v for k, v in bound.items() if k != "admission"}, budget,
                            quality_record=admission.get("quality_record"), authorization=admission.get("authorization"))
        if not gate["accepted"]: raise SchemaError("learned v2 bundle requires accepted quality and bounded authorization")
    progress = deepcopy(supervision_progress) if supervision_progress is not None else empty_supervision_progress(model.config)
    if (progress.get("optimizer_steps") != optimizer_steps or not valid_supervision_coverage(progress.get("consumed"), model.config)
            or optimizer_steps == 0 and progress != empty_supervision_progress(model.config)):
        raise SchemaError("v2 bundle lacks matching committed supervision coverage")
    corpus = bound.get("training_supervision", supervision_coverage([], model.config))
    evidence = {"config_sha256": config_hash(model.config),
                "train_records_sha256": bound.get("splits", {}).get("train", {}).get("records_sha256"),
                "corpus": corpus, "progress": progress}
    output.mkdir(parents=True, exist_ok=True)
    _write_json(model.config, output / "config.json")
    atomic_save(model.state_dict(), output / "weights.pt")
    manifest = {**(metadata or {}), "format": "nosl.student.bundle.v2", "model_version": MODEL_VERSION,
                "public_schema": PUBLIC_SCHEMA, "status": "EXPERIMENTAL_UNPROMOTED", "trained": optimizer_steps > 0,
                "calibrated": False, "promoted": False, "formal_training_run": False,
                "config_sha256": config_hash(model.config),
                "weights_sha256": hashlib.sha256((output / "weights.pt").read_bytes()).hexdigest(),
                "implementation": inference_fingerprint(), "frozen_inputs": bound,
                "training_supervision": deepcopy(corpus), "supervision_progress": progress,
                "supervision_sha256": config_hash(evidence),
                "budget": deepcopy(budget), "optimizer_steps": optimizer_steps,
                "test_evaluated": False, "test_labels_read": False, "test_used_for_model_selection": False,
                "safe_learned_plan_execution_verified": False}
    _write_json(manifest, output / "manifest.json")
    return manifest


def pilot_train(datasets: dict, config: dict, output: str | Path, *, budget: dict,
                quality_record: dict | None = None, authorization: dict | None = None,
                resume: bool = False, stop_after_steps: int | None = None) -> dict:
    """Explicitly authorized bounded fitting only; budgets are lifetime limits."""
    if stop_after_steps is not None: integer(stop_after_steps, "stop_after_steps", 1, 50000)
    base = config["base_config"]
    seed_everything(base["seed"], base.get("torch_threads", 1))
    frozen = freeze_inputs(datasets, config)
    gate = quality_gate(frozen, budget, quality_record=quality_record, authorization=authorization)
    if not gate["accepted"]: raise SchemaError("v2 fit blocked: " + ", ".join(gate["reasons"]))
    frozen["admission"] = {"quality_record": deepcopy(quality_record), "authorization": deepcopy(authorization)}
    model = StudentV2(config)
    optimizer = torch.optim.AdamW(model.parameters(), lr=base["learning_rate"])
    output = Path(output)
    epoch, offset, steps, order, trace = 0, 0, 0, [], []
    progress = empty_supervision_progress(config)
    if resume:
        state = restore_checkpoint(output / "checkpoint.pt", model, optimizer, frozen, budget)
        epoch, offset, steps, order, trace = (state[k] for k in ("epoch", "offset", "optimizer_steps", "order", "trace"))
        progress = state["supervision_progress"]
        baseline = [entry for entry in trace if entry.get("phase") == "before_fit_random_initialization"]
        if len(baseline) != 1 or baseline[0].get("optimizer_steps") != 0 or baseline[0].get("epoch") != 0:
            raise SchemaError("v2 resume lacks one valid before-fit random-initialization reference")
    else:
        output.mkdir(parents=True, exist_ok=False)
        trace.append({"phase": "before_fit_random_initialization", "epoch": 0, "optimizer_steps": 0,
                      "validation": evaluate(model, datasets["validation"])})
        _write_json(config, output / "config.json")
        _write_json(frozen, output / "inputs.json")
        atomic_save(checkpoint_state(model, optimizer, frozen, budget, epoch, offset, steps, order, trace,
                                    supervision_progress=progress), output / "checkpoint.pt")
    initial_steps, started = steps, time.perf_counter()
    while epoch < budget["max_epochs"] and steps < budget["max_steps"]:
        if stop_after_steps is not None and steps - initial_steps >= stop_after_steps: break
        # Check source/config/input identity before every optimizer step as well
        # as on save. Modified shards or in-memory labels never produce a step.
        current = freeze_inputs(datasets, config)
        if current != {k: v for k, v in frozen.items() if k != "admission"}:
            raise SchemaError("v2 frozen inputs changed during pilot")
        if not order:
            order = list(range(len(datasets["train"])))
            random.shuffle(order)
        indices = order[offset:offset + base["batch_size"]]
        supervised = [i for i in indices if has_supervision(datasets["train"][i], config)]
        model.train()
        optimizer.zero_grad(set_to_none=True)
        train_loss = 0.0
        for index in supervised:
            record = datasets["train"][index]
            loss, _ = decision_loss(model(record["public_input"]), record["targets"], record["public_input"], config)
            if not torch.isfinite(loss): raise RuntimeError("non-finite v2 pilot loss")
            (loss / len(supervised)).backward()
            train_loss += float(loss.detach()) / len(supervised)
        if supervised:
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0, error_if_nonfinite=True)
            optimizer.step()
            steps += 1
            _record_committed_supervision(progress, [datasets["train"][i] for i in supervised], config)
        offset += len(indices)
        if offset == len(order):
            trace.append({"phase": "after_epoch", "epoch": epoch + 1, "optimizer_steps": steps,
                          "last_batch_train_loss": train_loss, "validation": evaluate(model, datasets["validation"])})
            epoch, offset, order = epoch + 1, 0, []
        atomic_save(checkpoint_state(model, optimizer, frozen, budget, epoch, offset, steps, order, trace,
                                    supervision_progress=progress), output / "checkpoint.pt")
        _write_json(trace, output / "metrics.json")
    final_validation = evaluate(model, datasets["validation"])
    atomic_save(checkpoint_state(model, optimizer, frozen, budget, epoch, offset, steps, order, trace,
                                supervision_progress=progress), output / "checkpoint.pt")
    _write_json(trace, output / "metrics.json")
    return export_bundle(model, output, frozen=frozen, budget=budget, optimizer_steps=steps, supervision_progress=progress,
                         metadata={"pilot_trial": True, "validation_before_fit": trace[0]["validation"],
                                   "validation": final_validation, "epochs_completed": epoch, "next_offset": offset,
                                   "wall_seconds_this_invocation": time.perf_counter() - started,
                                   "budget_exhausted": steps >= budget["max_steps"] or epoch >= budget["max_epochs"]})


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True)
    parser.add_argument("--prepared", required=True)
    parser.add_argument("--mode", choices=("readiness", "pilot", "formal"), default="readiness")
    parser.add_argument("--quality-acceptance")
    parser.add_argument("--authorization")
    parser.add_argument("--max-steps", type=int)
    parser.add_argument("--max-epochs", type=int)
    parser.add_argument("--max-roots", type=int)
    parser.add_argument("--output")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--stop-after-steps", type=int)
    args = parser.parse_args()
    if args.mode == "formal": parser.error("formal v2 training is disabled")
    from .data_v2 import PreparedDatasetV2
    config = load_config(args.config)
    base = config["base_config"]
    seed_everything(base["seed"], base.get("torch_threads", 1))
    datasets = {split: PreparedDatasetV2(args.prepared, split, config) for split in ("train", "validation")}
    frozen = freeze_inputs(datasets, config)
    budget = ({"max_steps": args.max_steps, "max_epochs": args.max_epochs, "max_roots": args.max_roots}
              if any(value is not None for value in (args.max_steps, args.max_epochs, args.max_roots)) else None)
    quality = json.loads(Path(args.quality_acceptance).read_text()) if args.quality_acceptance else None
    authorization = json.loads(Path(args.authorization).read_text()) if args.authorization else None
    if args.mode == "readiness":
        result = {"status": "READINESS_ONLY", "optimizer_steps": 0, "weights_written": False,
                  "formal_training_run": False, "frozen_inputs": frozen,
                  "quality_gate": quality_gate(frozen, budget, quality_record=quality, authorization=authorization)}
    else:
        if not args.output: parser.error("bounded pilot requires --output")
        result = pilot_train(datasets, config, args.output, budget=budget, quality_record=quality,
                             authorization=authorization, resume=args.resume, stop_after_steps=args.stop_after_steps)
    print(json.dumps(result, allow_nan=False))


if __name__ == "__main__": main()
