namespace STS2BestChoice.Core.Scoring;

/// <summary>
/// Intrinsic per-turn value from the status owner's perspective. Positive values
/// help the owner; negative values harm the owner. Enemy-owned values are inverted
/// once by <see cref="CombatScorer"/>.
/// </summary>
internal static class StatusValuation
{
    public static decimal IntrinsicFutureValue(string? statusId, decimal amount)
    {
        var magnitude = Math.Abs(amount);
        return statusId?.ToUpperInvariant() switch
        {
            "STRENGTH" => amount * 1.5m,
            "TEMP_STRENGTH_LOSS" => -magnitude * 1.5m,
            "DEXTERITY" => amount * 1.25m,
            "FOCUS" => amount * 1.5m,
            "INTANGIBLE" => magnitude * 4m,
            "THORNS" => amount * 0.75m,
            "PLATED_ARMOR" => amount,
            "VIGOR" => amount * 0.5m,
            "TURN_START_VIGOR" => amount,
            "TURN_START_DEXTERITY_LOSS" => -amount * 1.25m,
            "TURN_START_FOCUS_LOSS" => -amount * 1.5m,
            "TURN_START_BLOCK" => amount,
            "TURN_START_SELF_HP_LOSS" => -amount * 4m,
            "TURN_START_GENERATE_SHIV" => amount * 2m,
            "TURN_START_ALL_ENEMY_POISON" => amount * 2m,
            "MAX_ENERGY_DELTA" => amount * 3m,
            "HAND_DRAW_DELTA" => amount * 2m,
            "ITERATION_DRAW" => amount * 2m,
            "PAGESTORM_DRAW" => amount * 2m,
            "RADIANCE" => amount * 2m,
            "WEAK" => -magnitude * 1.5m,
            "FRAIL" => -magnitude * 1.5m,
            "VULNERABLE" => -magnitude * 2m,
            "POISON" => -magnitude,
            "DOOM" => -magnitude,
            "TURN_START_SELF_DOOM" => -magnitude,
            "STUN" => -magnitude * 4m,
            "CANNOT_DRAW" or "CANNOT_GAIN_ENERGY" => -magnitude * 3m,
            "NO_BLOCK_FROM_CARDS" => -6m,
            "DOUBLE_DAMAGE" => amount * 5m,
            "SHADOW_STEP_PENDING" => amount * 5m,
            "TRIGGER_ATTACK_DAMAGE_DOOM" => amount * 3m,
            "BONUS_WEAK_TARGET_POWERED_ATTACK_DAMAGE_PERCENT" => amount * 0.08m,
            "UNMOVABLE" => amount * 4m,
            "SHIV_DAMAGE_BONUS" => amount * 1.5m,
            "SHIV_ALL_ENEMIES" => amount * 4m,
            "SHIV_RETAIN" => amount * 2m,
            "FIRST_SHIV_DAMAGE_BONUS" => amount * 0.75m,
            "JUGGLING" => amount * 3m,
            "ACCELERANT" => amount * 2m,
            "THE_GAMBIT" => -amount * 4m,
            "LETHALITY" => amount * 0.08m,
            "PALE_BLUE_DOT" => amount * 2m,
            "ONE_FOR_ALL" => amount * 1.5m,
            "FASTEN" => amount * 1.25m,
            "HELLRAISER" => amount * 3m,
            "TURN_END_RANDOM_HAND_ATTACK" => amount * 3m,
            "BONUS_VULNERABLE_POWERED_ATTACK_DAMAGE_PERCENT" => -amount * 0.08m,
            "HANG_DAMAGE_MULTIPLIER" => -(Math.Max(1m, amount) - 1m) * 3m,
            "REDUCE_VULNERABLE_ATTACK_DAMAGE" => amount * 3m,
            "REFLECT_BLOCKED_ATTACK_DAMAGE" => amount * 3m,
            "ALL_CARD_COST_DELTA" => -amount * 3m,
            "DOUBLE_BLOCK_GAINED" => amount * 2m,
            "TURN_START_ENERGY" => amount * 3m,
            "TURN_START_DRAW" => amount * 2m,
            "AUTOMATION_DRAW_ENERGY" => amount * 1.5m,
            "ORBIT_ENERGY_REBATE" => amount * 2m,
            "SKILLS_COST_ZERO" or "SKILLS_EXHAUST_ON_PLAY" => amount * 3m,
            "BARRICADE" => amount * 3m,
            "BLUR" => amount * 2m,
            "FERAL_ZERO_COST_ATTACK_RETURN" or "NOSTALGIA_ATTACK_SKILL_TOPDECK" => amount * 2m,
            "ECHO_FORM_REPLAY_FIRST_CARDS" => amount * 4m,
            "NEXT_ATTACK_REPLAY" or "NEXT_SKILL_REPLAY" or "NEXT_POWER_REPLAY" or "NEXT_CARD_REPLAY" => amount * 3m,
            "NEXT_FREE_ATTACK" or "NEXT_FREE_SKILL" or "NEXT_FREE_POWER" or "NEXT_FREE_ETHEREAL" => amount * 3m,
            "NEXT_CARD_TO_DRAW_TOP" => amount * 1.5m,
            "TRIGGER_CARD_PLAYED_BLOCK" or "TRIGGER_ATTACK_PLAYED_BLOCK" or
            "TRIGGER_POWER_PLAYED_LIGHTNING" or "TRIGGER_POWER_PLAYED_ENERGY" => amount * 2m,
            "TRIGGER_ETHEREAL_PLAYED_BLOCK" or "TRIGGER_ENERGY_AT_LEAST_2_BLOCK" => amount,
            "TORIC_TOUGHNESS" => amount * 0.8m,
            "THE_BOMB" => amount * 0.7m,
            "POWERS_COST_DELTA" => amount * 3m,
            "WELL_LAID_PLANS" => amount * 2.5m,
            "TOOLS_OF_THE_TRADE" => amount * 2.5m,
            "DEBILITATE" => -amount * 3m,
            "KINGS_BLADE_DOUBLE_DAMAGE" => amount * 2.5m,
            "KINGS_BLADE_ALL_ENEMIES" => 3.0m,
            "KINGS_BLADE_BLOCK" => amount * 2.0m,
            "KINGS_BLADE_REPLAY" => amount * 3.0m,
            "KINGS_BLADE_COST_DELTA" => -amount * 2.0m,
            "STARS" => amount * 2.0m,
            "BLACK_HOLE" => amount * 2.5m,
            "CHILD_OF_THE_STARS" => amount * 2.0m,
            "MASTER_PLANNER" => 2.5m,
            "SHROUD" => amount * 2.0m,
            "SLEIGHT_OF_FLESH" => amount * 2.0m,
            "THUNDER" => amount * 2.0m,
            "TRASH_TO_TREASURE" => 2.5m,
            "CALCIFY" => amount * 1.5m,
            "NECRO_MASTERY" => 3.0m,
            "ROLLING_BOULDER" => amount * 2.0m,
            "CALL_OF_THE_VOID" => 2.5m,
            "DRAW_CARD_REPLAY" => amount * 2.0m,
            "SIC_EM" => amount * 2.0m,
            "FOREGONE_CONCLUSION" => amount * 2.5m,
            "FORBIDDEN_GRIMOIRE" => 3.0m,
            "ENTROPY" => amount * 2.0m,
            "NIGHTMARE" => 3.5m,
            "DISCOVERY" => 2.5m,
            "QUASAR" => 2.5m,
            "SPLASH" => 2.5m,
            "TYRANNY" => 2.5m,
            "VOID_FORM" => 4.0m,
            "STRATAGEM" => 2.5m,
            "ABUNDANCE" => 3.0m,
            "CONSUMING_SHADOW" => amount * 3.5m,
            "SENTRY_MODE" => amount * 4.0m,
            "DEVOUR_LIFE" => amount * 2.0m,
            "GENESIS" => amount * 2.0m,
            "THE_SEALED_THRONE" => amount * 3.0m,
            "FURNACE" => amount * 1.5m,
            "SPINNER" => amount * 3.0m,
            "CALAMITY" => amount * 3.0m,
            "CREATIVE_AI" => amount * 3.5m,
            "HELLO_WORLD" => amount * 2.0m,
            "SPECTRUM_SHIFT" => amount * 2.5m,
            _ => 0m
        };
    }
}
